### ISSUE TITLE
Why mul_by_a in CurveHooks?

### ISSUE THREAD

**Issue by burdges** [paritytech/ark-substrate#21]
It's clear why arkworks has `mul_by_a` exists in `short_weierstrass::SWCurveConfig` and `twisted_edwards::TECurveConfig` in `ark_ec::models`:  

> The default implementation should be overridden only if the product can be computed faster than standard field multiplication (eg: via doubling if `COEFF_A == 2`, or if `COEFF_A.is_zero())`.

Why does `mul_by_a` exist in our `CurveHooks` though?  We must override `mul_by_a` for the BLS and BW curves, but we push this through directly, never even invoking the `CurveHooks` version: https://github.com/search?q=repo%3Aparitytech%2Farkworks-extensions%20mul_by_a&type=code

It's perhaps legacy from when w explored generic multi-curve host calls?  I'm unsure why it'd appear there, especially without `add_b`.

**Comment by davxy** [comment]
We're forwarding it to the specialized implementations provided by arkworks for each of the curves (as you noted).
The reason to have it is because we otherwise end up jumping into the trait default implementation (which is a bit smart only for SwConfig)

https://github.com/arkworks-rs/algebra/blob/273bf2130420904cab815544664a539f049d0494/ec/src/models/short_weierstrass/mod.rs#L43-L49

https://github.com/arkworks-rs/algebra/blob/273bf2130420904cab815544664a539f049d0494/ec/src/models/twisted_edwards/mod.rs#L42-L44

**Comment by davxy** [comment]
Just to be clear, `mul_by_a` doesn't exist in `CurveHooks`. We're just overwriting `mul_by_a` default implementation provided by arkworks `*CurveConfig` so that we jump into the optimized version  provided by the specific curve

**Comment by burdges** [comment]
Ahh oops yes, I must've missread it before, thought I'd seen a `mul_by_a` in `CurveHooks`
